import { garageNeighbourhoodCoverage } from "./neighbourhoodCoverage";
// Each city has its own repair decision and estimate brief; no inferred local building conditions.
const cityContent = [
  {
    slug: "mississauga", name: "Mississauga", focus: "Peeling wall tape and a clear repair boundary",
    description: "Garage drywall repair in Mississauga for peeling tape, damaged joints and rough walls. Compare localized re-taping with broader finishing and painting prep.",
    intro: "For garage drywall repair in Mississauga, start by separating loose tape from sound but rough finishing. EPF can assess the affected joints and quote either defined local repairs or a wider surface improvement, with primer and paint included only when specified.",
    answer: "A peeling seam on sound board may be repaired locally. The scope can extend past the curled edge to reach a suitable joint, then blend into retained finishing. Mark each damaged wall and show how shelving or vehicles affect access.",
    sections: [
      { title: "Map the peeling joints before clearing the garage", paragraphs: ["Take a wide photograph of each wall before moving belongings, then identify the seams you can actually see. A close-up of curled tape is useful, but the estimator also needs to know whether the strip continues behind shelving or turns across the ceiling. Numbering the photos makes a short defect list easier to discuss.", "Do not count all visible compound as failed work. Unpainted stripes can be sound even when their appearance is rough. The assessment should separate detached tape, shallow surface marks and optional refinishing. That distinction gives the homeowner control over the essential repair scope and the appearance upgrade."] },
      { title: "Compare two finishing boundaries", paragraphs: ["One option may rebuild only the failed joints and leave the rest of the garage in its existing condition. Another may blend the repaired wall and prepare the whole plane for a new coating. Ask where each option stops: at the sound joint, an inside corner, a doorway or the entire wall.", "A small repair does not guarantee an invisible paint touch-up. If the original coating is aged or its product is unknown, repainting a larger plane may be needed for a consistent appearance. Decide whether EPF or your painter handles that stage before accepting the repair-only price."] },
      { title: "What to send for a Mississauga estimate", paragraphs: ["Include wall and ceiling height, the approximate length of affected seams, access around storage and whether the garage is painted. Note previous repairs and any history of staining. A planned vehicle move or shelf removal should be confirmed, not assumed available on the first workday.", "Your quote should identify assessment, necessary board corrections, re-taping, finishing and the selected decorating handoff. Where a condition is concealed, agree on how additional findings will be reviewed before the work expands. This keeps the scope concrete while allowing the repair boundary to follow the actual condition."] }
    ],
    faqs: [["Can you repair peeling garage tape without refinishing every wall?", "A local scope can be considered if surrounding board and joints are suitable. Confirm the repair and painting boundaries; blending can extend beyond the visibly loose strip."],["Should I remove garage shelves before the estimate?", "Start with photographs showing the shelves and access. Agree on what needs removal for assessment and work; do not dismantle fixed or loaded systems simply to expose a seam."],["Does a garage repair include wall painting?", "Only when the quote includes it. Specify sanded repair, primer or completed paint, including the surface area to be decorated."]],
    guides: ["why-garage-drywall-tape-peels", "garage-drywall-repair-cost-factors"]
  },
  {
    slug: "oakville", name: "Oakville", focus: "Rough joints before a smooth painted finish",
    description: "Garage drywall repair in Oakville for rough seams, visible patches and peeling tape. Plan sound repairs, finish levels and a clear primer-to-paint handoff.",
    intro: "EPF provides garage drywall repair in Oakville for homeowners preparing rough or previously patched walls for painting. We review the joints first, then define the surface finishing needed for your chosen lighting, paint and use of the garage.",
    answer: "Visible joints do not always mean the drywall needs replacement. Sound rough finishing may be improved; loose tape needs repair before smoothing. Select the finish around the planned decoration rather than assuming every wall needs a full skim coat.",
    sections: [
      { title: "Separate a finish upgrade from joint failure", paragraphs: ["A painted garage wall may show a narrow ridge or a broad old patch without the material being detached. Ask for those appearance concerns to be assessed separately from bubbling or loose tape. The first can involve surface shaping; the second needs the failed bond addressed before the final finish is built.", "When the goal is a clean workshop or finished storage space, show the estimator which walls will remain visible. A whole-garage appearance specification may be useful, but a selected-wall scope can also be discussed. Neither should conceal unresolved moisture, loose board or an unsuitable original coating."] },
      { title: "Choose light and paint before the last coat", paragraphs: ["Share the planned paint sheen and lighting positions for your Oakville garage. Light travelling along a wall can reveal a transition that is less apparent under even illumination. A sample can help establish expectations before a large surface is refinished, particularly if the decorating choice is demanding.", "Level 5 adds whole-surface skim treatment after the necessary joint finishing; it does not straighten a badly aligned wall. A standard finish may be sufficient elsewhere. Put the selected treatment beside each wall or ceiling in the scope so an upgrade is measured on the surfaces that receive it."] },
      { title: "Agree on the inspection after primer", paragraphs: ["Primer can reveal small scratches, pinholes or differences that were less visible on raw compound. Arrange who will inspect, correct and spot-prime those areas. If a separate painter is involved, the handoff should identify responsibilities before the finishing crew leaves.", "Send full wall views, close-ups of ridges or failed tape, ceiling dimensions and the intended coating. Include any existing paint information. An estimate can then distinguish repair work, optional broad finishing and painting, instead of packaging every concern under an undefined promise of smooth walls."] }
    ],
    faqs: [["Does every Oakville garage need Level 5 finishing?", "No. The choice depends on decoration, light and the desired appearance. Sound repairs and an appropriate standard finish may be sufficient; discuss any full skim by surface."],["Can old patch lines be made less visible?", "The wall can be assessed for reshaping, blending and primer preparation. A coating mismatch may also require repainting beyond the patch."],["Can the garage ceiling have a different finish from the walls?", "Yes, if the specification suits the intended decoration and applicable construction requirements. Record the finish for each plane."]],
    guides: ["garage-drywall-finishing-levels", "fix-bad-drywall-finishing-garage", "garage-drywall-repair-before-painting"]
  },
  {
    slug: "burlington", name: "Burlington", focus: "Repairs around an occupied garage and retained storage",
    description: "Garage drywall repair in Burlington with a plan for storage, vehicle access and phased work. Re-taping, wall repairs and finishing with clear boundaries.",
    intro: "Garage drywall repair in Burlington can be planned around the way your household uses the space. EPF assesses damaged walls and seams alongside stored items, the route into the house and the work area needed for coating and sanding.",
    answer: "A repair needs room for protection and finishing beyond the damaged spot. If storage or vehicle access must continue, define work phases and temporary closures before pricing. Shared ceilings and continuous walls need sensible finishing boundaries.",
    sections: [
      { title: "Make access part of the repair scope", paragraphs: ["Show the garage as it is normally used, including shelves, freezers, benches and the route to the house. An empty-looking close-up can hide the amount of preparation around a seam. Tell the estimator which items can move and which need to remain accessible throughout the project.", "Protection is part of a work plan, not permission to keep using an active repair area. Agree on when vehicles and household traffic must stay outside. EPF can discuss dust-controlled sanding and containment appropriate to the scope; no repair process makes the surrounding garage completely dust-free."] },
      { title: "Avoid an arbitrary stop halfway across a wall", paragraphs: ["A phased Burlington garage repair can work when the boundaries are clear. However, one continuous ceiling or wall may need blending past the edge of the first phase. A later repair beside freshly finished work can require protection and decorating that overlap the earlier stage.", "Ask for the difference between one continuous work window and separate visits around storage access. Additional setup and cleanup may change the total even when the damaged seam length stays the same. Compare complete scopes rather than expecting each half to cost exactly half the uninterrupted job."] },
      { title: "Plan the waiting periods", paragraphs: ["During drying intervals, the surface and protection still need suitable conditions. Ask which routes may reopen and what must remain undisturbed. Work visits, elapsed drying time and the date the garage can be used normally are different points in the schedule.", "For an estimate, send a sketch of the storage and access routes with the affected walls marked. Include ceiling damage, approximate heights and your desired finish. A clear phase plan helps keep the repair scope predictable without promising unrestricted access during sanding or overhead work."] }
    ],
    faqs: [["Can I keep a vehicle in the garage during repairs?", "Access depends on the work area and stage. Plan for removal during active work where needed; a cover is not a substitute for safe workspace."],["Can garage wall repairs be completed in phases?", "Possibly. Choose boundaries that allow proper blending and account for repeated setup, protection and painting."],["Will HEPA sanding eliminate garage dust?", "Dust extraction reduces spread but does not eliminate it. Protection, controlled access and cleanup remain necessary."]],
    guides: ["garage-drywall-repair-cost-factors", "drywall-repair-vs-skimming-garage-walls"]
  },
  {
    slug: "hamilton", name: "Hamilton", focus: "Previous repairs and seams that reopen",
    description: "Garage drywall repair in Hamilton for recurring cracks, failed patches and loose tape. Assess previous work before re-taping, board correction and finishing.",
    intro: "For garage drywall repair in Hamilton, EPF can review seams and patches that have already been repaired once. We use the visible condition and available repair history to define what needs correction before another finish coat is applied.",
    answer: "A recurring line needs more than a repeat of the previous cosmetic treatment. Record when it reopened and what was done before. Loose material, board condition and possible outside causes should be assessed before the finishing scope is agreed.",
    sections: [
      { title: "Bring the earlier repair into the assessment", paragraphs: ["If you have photos from before and after the last repair, keep them together. Note how long the finish looked acceptable and whether the defect returned in the same location or beside the patch. This information helps frame the investigation without assigning blame to a previous homeowner or contractor.", "A raised patch, reopened crack and loose tape edge are different observations. Describe each one plainly. Avoid covering the line or scraping away every compound ridge before review; doing so can remove useful evidence and change the scope of the work needed."] },
      { title: "Define what can remain", paragraphs: ["Sound surrounding finishing may be retained, while unsuitable repair material needs an appropriate boundary. An assessment should explain whether the issue is limited to surface shaping, failed reinforcement or a base that needs correction. It should also identify conditions that cannot be resolved by a finisher alone.", "A quote for your Hamilton garage should separate removal or preparation, any necessary board work, re-taping and decoration. Where the cause is uncertain, arrange the next assessment before agreeing that one more coat will be the final solution. A repair specification cannot guarantee that concealed movement has stopped."] },
      { title: "Document the new handoff", paragraphs: ["Keep photographs of the agreed repair area and a written description of the finishing boundary. Identify who handles any related trade work and who checks the surface after primer. If new damage occurs during a later installation, record it separately from the original defect.", "Send full wall and ceiling views, repair history, any product labels and your planned painting date. Mention staining, seasonal changes or a loose area. This gives EPF a more useful starting point than a request to cover the same line again."] }
    ],
    faqs: [["Can you review a garage repair completed by another contractor?", "Yes, EPF can assess visible conditions and discuss a suitable scope. Share the original repair description and photos if available."],["Should I sand off the old patch before the estimate?", "Leave uncertain materials for assessment. Unplanned sanding can remove evidence and create additional damage or dust."],["Can you guarantee a recurring crack will never return?", "No blanket promise can account for unresolved movement or concealed conditions. The repair should follow assessment and a defined scope."]],
    guides: ["garage-drywall-tape-repair-keeps-failing", "garage-drywall-seams-cracking", "retape-or-replace-garage-drywall"]
  },
  {
    slug: "milton", name: "Milton", focus: "From utility finishing to a painted garage",
    description: "Garage drywall repair in Milton for unfinished joints, rough compound and failed tape. Plan a practical upgrade from utility surfaces to paint-ready walls.",
    intro: "EPF provides garage drywall repair in Milton for unfinished or rough surfaces that need attention before painting. We distinguish sound utility finishing from failed tape, then price the repair and appearance work required for your next use of the space.",
    answer: "Visible compound stripes are not automatically failed drywall. If you want a painted garage, the surface may need additional joint finishing, fastener treatment and preparation. Loose tape or damaged board must be corrected before an appearance upgrade.",
    sections: [
      { title: "Decide what finished means for your garage", paragraphs: ["A garage used mainly for parking may have different appearance priorities from a bright work area. Name the surfaces you will see, the walls behind fixed storage and whether the ceiling belongs in the project. This keeps an improvement scope tied to your use rather than a generic premium finish label.", "Existing rough work should be assessed without assuming it was intended to look like a decorated living room. The question is whether it is sound and what additional finishing is needed for the new specification. Whole-surface smoothing is optional where appropriate; joint repairs are a separate decision."] },
      { title: "Finish the visible details as well as the broad wall", paragraphs: ["Outside corners, short doorway returns and fastener spots can remain conspicuous after the main seams are improved. Include those details in your Milton garage estimate. A room photograph should show transitions as well as large flat surfaces, especially where new finishing meets retained work.", "Confirm whether the quoted finish stops before primer. If you plan to paint yourself, ask what dust removal and surface checks remain. The coating product's instructions still apply to preparation and conditions, even when the garage has just been sanded."] },
      { title: "Keep essential repair and optional finish separate", paragraphs: ["Ask for the failed joints and damaged board to be identified first. Then compare the appearance options on that repaired base. This helps avoid choosing a broad skim allowance that leaves loose reinforcement underneath it, or replacing sound board simply because its current finish is unattractive.", "Send wide photos of the unfinished garage, close views of suspect joints and your intended paint and lighting. Mention whether the space can maintain suitable working conditions. EPF can use those details to discuss a defined path from existing utility surfaces to your chosen handoff."] }
    ],
    faqs: [["Is visible mud on an unfinished garage wall a defect?", "Not necessarily. It may reflect the original utility finish. Assessment should distinguish sound rough work from detached tape or damaged board."],["Can you prepare garage walls for homeowner painting?", "A preparation-only scope can be discussed. Confirm sanding, dust removal, primer responsibility and the correction process."],["Should unfinished garage ceilings be included?", "Only if you want them in the scope. Identify ceiling planes, returns and the intended finish separately."]],
    guides: ["fix-bad-drywall-finishing-garage", "garage-drywall-finishing-levels"]
  },
  {
    slug: "toronto", name: "Toronto", focus: "Ceiling joints and restricted work access",
    description: "Garage drywall repair in Toronto for ceiling tape, seam cracks and wall damage. Plan access around tracks, storage and fixtures before re-taping and finishing.",
    intro: "Garage drywall repair in Toronto can involve awkward overhead joints and limited space around stored equipment. EPF reviews the ceiling or wall defect together with access, so the repair plan accounts for the areas that need to be reached and protected.",
    answer: "Ceiling tape can be assessed for local repair when the board is suitable. Door tracks, lighting and storage affect access. Sagging or loose board needs assessment before normal finishing, and door hardware should be handled by the appropriate trade.",
    sections: [
      { title: "Show the ceiling and the route beneath it", paragraphs: ["A photograph straight up at peeling tape does not show the room needed for access. Include a wide view from the entrance and both sides of the garage, with the tracks and fixtures visible. Indicate which items can be moved before the work and which are fixed.", "Do not alter garage door springs, tracks or electrical equipment to expose a seam. If access requires changes, coordinate the appropriate specialist. The drywall scope should explain where that coordination ends and the finishing work begins."] },
      { title: "Separate overhead tape from loose board", paragraphs: ["A short hanging strip does not tell you whether the ceiling panel is stable. Visible sagging, detachment or wet material changes the assessment. Keep clear of a suspect area and arrange appropriate review; do not treat it as a routine ladder-and-paint task.", "Where the board is suitable, the proposal may include removing failed tape, preparing the joint and rebuilding the finish. The repair can extend along the seam beyond the visible flap. Ask how the transition will be checked under the lighting that will remain in your Toronto garage."] },
      { title: "Price the ceiling plane and decoration together", paragraphs: ["An isolated ceiling seam repair can be separate from full ceiling painting, but the handoff should be explicit. Spot decorating may differ from aged surrounding paint. If you want a consistent finished plane, have the full coating area described before comparing totals.", "Send ceiling height, approximate affected lengths, access photos and any history of leaks or earlier repairs. Include the wall-to-ceiling corners if they also need attention. This helps EPF distinguish a local joint repair from a broader overhead restoration."] }
    ],
    faqs: [["Can you repair tape near garage door tracks?", "The area needs an access review. Door hardware changes belong with the appropriate specialist; the drywall repair scope should account for that coordination."],["Does loose ceiling tape mean the board must be replaced?", "Not by itself. Board condition and attachment need assessment. Sagging or compromised material changes the repair decision."],["Will only the repaired ceiling strip be painted?", "That depends on the scope. Discuss whether a local touch-up can meet the appearance target or the full plane needs repainting."]],
    guides: ["garage-ceiling-drywall-tape-coming-loose", "retape-or-replace-garage-drywall"]
  },
  {
    slug: "etobicoke", name: "Etobicoke", focus: "Impact damage and wall patch boundaries",
    description: "Garage drywall repair in Etobicoke for impact holes, damaged board and visible old patches. Define supported repairs, blending and the painting boundary.",
    intro: "EPF handles garage drywall repair in Etobicoke for damaged wall sections, failed patches and nearby seam problems. We assess the retained board and repair boundary before agreeing how the patch will blend into the surrounding wall.",
    answer: "An impact hole can sometimes be repaired locally, but support, surrounding damage and existing construction determine the method. Painting and surface blending may extend farther than the board patch itself.",
    sections: [
      { title: "Distinguish the hole from the finishing area", paragraphs: ["The visible opening is only one part of the repair. A patch needs suitable support and a workable joint boundary, while compound coats need room to blend outward. If a hole sits beside a corner or behind a bench, show those details in the estimate photos.", "Do not trim an opening or add random fasteners before concealed services and construction are understood. A small damaged area may still involve an assembly that needs a particular repair detail. The appropriate method should be assessed before a cosmetic cover is installed."] },
      { title: "Review older patches beside the new damage", paragraphs: ["If an old repair already shows through paint, decide whether it belongs in the new Etobicoke garage scope. Ask for an optional allowance rather than assuming all previous imperfections will be corrected while the crew is present. The old patch may require a different treatment from the fresh impact damage.", "A sound but raised patch can need surface reshaping; a loose edge needs a bond assessment. Broad sanding alone may damage surrounding paper without correcting the cause. Define which areas are retained and what result is expected once primer is applied."] },
      { title: "Plan the wall finish after the patch", paragraphs: ["If the paint is unknown or weathered, a small colour match may remain visible. Discuss repainting to a natural wall boundary and include preparation of the surrounding surface. The patch size and the final decorating area need not be identical.", "For your estimate, send one full-wall photo, a close view of the opening and a view showing shelves or other obstructions. Include approximate dimensions and whether the wall has moisture history. EPF can then discuss the board repair, finishing and optional coating as clear stages."] }
    ],
    faqs: [["Can a garage impact hole be repaired without replacing the wall?", "A local patch can be assessed when surrounding construction is suitable. Support, concealed services and assembly requirements guide the repair."],["Is the painted area the same size as the patch?", "Not necessarily. Blending and repainting may extend to a larger natural boundary for a consistent result."],["Can you improve an old patch while repairing new damage?", "Yes, it can be assessed as a named addition. Its condition and finishing needs may differ from the new hole."]],
    guides: ["retape-or-replace-garage-drywall", "garage-drywall-repair-before-painting"]
  },
  {
    slug: "north-york", name: "North York", focus: "Workshops, shelving and selective wall refinishing",
    description: "Garage drywall repair in North York for workshop walls, loose seams and rough finishing. Plan repair access and selected surfaces before shelving or painting.",
    intro: "For garage drywall repair in North York, EPF can plan the work around a workshop or storage upgrade. Repairing seams before new shelving and painting helps avoid a second finishing job around newly installed equipment.",
    answer: "Identify the walls that need repair before finalizing the storage layout. Loose tape needs assessment even where a cabinet may conceal it. New attachments, electrical changes and drywall finishing should have a coordinated sequence.",
    sections: [
      { title: "Review walls before installing the storage system", paragraphs: ["Photograph each wall before new cabinets or shelves restrict access. Mark the damaged joints and the areas that will remain visible after installation. A finisher needs enough working room to blend a repair; a narrow gap beside a fixed cabinet can change what is practical.", "Do not use new cabinetry to conceal a suspect wall without assessment. The appearance of the hidden area may be a lower priority, but its condition and any applicable construction requirements still matter. Keep those decisions separate in the project scope."] },
      { title: "Coordinate openings before the last finish coat", paragraphs: ["If the workshop plan includes electrical or other service changes, have the responsible trade confirm locations and timing. New cut-outs after refinishing can create fresh patches and another painting boundary. Required access points should remain identifiable throughout the work.", "EPF's North York garage repair scope can distinguish existing failed seams from openings left by other trades. Record what must be complete before finishing starts, then agree how any later change will be priced and scheduled. The drywall contractor should not be expected to guess future fixture locations."] },
      { title: "Choose selected walls or a complete finish", paragraphs: ["A workshop feature wall under directed light may need a more careful appearance discussion than an obscured storage wall. Explain the intended lighting and paint rather than requesting the same upgrade everywhere. A sample can help where expectations are demanding.", "Send a simple layout, wall heights, repair photos and the planned order of trade work. Include the storage system's footprint without asking the finisher to design its attachments. A clear plan lets the repair, decoration and installation stages connect without unnecessary repeat visits."] }
    ],
    faqs: [["Should drywall repairs happen before garage shelving is installed?", "Usually the repair needs access before fixed storage restricts it. Coordinate the sequence and confirm any required openings or attachments with the responsible trade."],["Can only the visible workshop wall be refinished?", "A selected-surface scope can be considered. Essential defects and construction requirements should still be addressed separately."],["Who handles electrical openings in the garage wall?", "The appropriate electrical trade handles electrical work. Drywall patching and finishing can be coordinated afterward, with boundaries stated in the quote."]],
    guides: ["drywall-repair-vs-skimming-garage-walls", "garage-drywall-repair-before-painting"]
  },
  {
    slug: "grimsby", name: "Grimsby", focus: "Localized seam repair and small-job scope",
    description: "Garage drywall repair in Grimsby for a few failed seams, local wall damage or ceiling tape. Compare a defined repair scope with optional wider refinishing.",
    intro: "Garage drywall repair in Grimsby does not have to begin with a whole-garage renovation. EPF can assess specific seams or damaged areas and explain the difference between a limited repair and optional broader finishing.",
    answer: "List the defects you want repaired and keep optional appearance work separate. A small scope still needs protection, drying and return visits, so garage floor area alone is not a useful repair-price calculation.",
    sections: [
      { title: "Name each repair instead of estimating by floor area", paragraphs: ["For a small Grimsby garage job, mark each failed seam or patch on a sketch. Include whether it is on the wall, ceiling or a corner and whether access is clear. Two short overhead repairs can have a different scope from one accessible wall joint of the same total length.", "Ask the estimator to separate essential corrections from optional rough-joint improvement. This avoids an open-ended instruction to fix everything while still making room to discuss the visible areas you care about most."] },
      { title: "Compare the project minimum with the complete scope", paragraphs: ["Small repair work can require material preparation, protection and several readiness-dependent visits. Those tasks do not shrink in direct proportion to the damaged area. No fixed minimum is advertised on this page; the written total should explain what the crew will complete.", "If another nearby patch also needs attention, have it assessed as an optional addition. Shared setup may help, but extra protection or painting can change the economics. Compare a repair-only total and a clearly itemized expanded scope rather than assume every extra patch is negligible."] },
      { title: "Choose the stopping point before booking painting", paragraphs: ["A defined local repair can stop at sanded drywall or include primer and coating. Agree on the inspection and whether decoration continues across a whole wall. A neat repair and a matching old paint touch-up are separate parts of the final appearance.", "Send full garage views, the marked defects, approximate heights and your preferred handoff. Tell EPF which areas will remain unfinished. That information supports a practical repair assessment without turning a few seams into a larger project you did not intend."] }
    ],
    faqs: [["Can you quote just a few garage seams in Grimsby?", "Yes, a defined local scope can be assessed. Include all affected lengths, access and the chosen finishing handoff."],["Is a small garage repair priced by floor size?", "Floor size does not capture repair condition, overhead work, protection or return visits. A written project scope is more useful."],["Can extra wall patches be added to the same job?", "Have them assessed and named in the quote. Shared setup is possible, but extra preparation and decoration may change the total."]],
    guides: ["garage-drywall-repair-cost-factors", "why-garage-drywall-tape-peels"]
  },
  {
    slug: "st-catharines", name: "St. Catharines", focus: "Drywall restoration after the moisture source is addressed",
    description: "Garage drywall repair in St. Catharines after moisture issues are addressed. Assess damaged board, repair boundaries, replacement and paint-ready finishing.",
    intro: "EPF provides garage drywall repair in St. Catharines, including assessment of the interior finish after a moisture problem has been addressed. The repair scope depends on the condition of affected board and surrounding construction, not the size of the visible stain alone.",
    answer: "Do not hide an unresolved leak or damp area under new compound. First arrange assessment of the source and affected materials. EPF can then discuss the drywall replacement, joint repair and finishing that are appropriate to the confirmed scope.",
    sections: [
      { title: "Confirm readiness before cosmetic restoration", paragraphs: ["Keep the history of the moisture event and any completed source repair with your photos. Describe whether the area is still changing or whether further investigation is planned. A dry-looking painted surface does not establish the condition behind it.", "If there is active moisture, visible suspect growth, soft board or uncertain supporting construction, arrange the relevant professional assessment before finishing. This service does not replace leak repair or hazardous-material evaluation, and a website estimate cannot certify a concealed area as ready."] },
      { title: "Choose a replacement boundary from condition", paragraphs: ["Some affected areas require board replacement rather than a skim over stained or weakened material. The boundary should follow sound construction and permit suitable support and finishing. A narrow strip chosen only to minimize paint work may not be the appropriate repair.", "Attached-garage assembly requirements also need to be preserved. Share drawings or known construction details when available. The correct repair does not follow a universal thickness or rating stated online; it depends on the existing project and applicable requirements."] },
      { title: "Separate restoration from the appearance upgrade", paragraphs: ["Once the repair base is suitable, decide whether EPF should restore the affected area or improve additional rough walls in your St. Catharines garage. The necessary replacement and the optional broader finish should remain identifiable in the quote.", "Send wide views, close-ups, approximate damaged dimensions and information about the resolved source. Include the intended primer and paint handoff. Confirm who reviews any new findings before the repair expands so restoration follows evidence rather than assumptions about what lies behind the stain."] }
    ],
    faqs: [["Can you refinish garage drywall before a leak is fixed?", "Cosmetic finishing should wait until the source is addressed and affected materials are assessed. Otherwise the underlying problem may remain."],["Does a dry stain mean the drywall can stay?", "Not necessarily. Surface appearance alone cannot establish the condition of the board or concealed construction."],["Can you quote replacement and wider garage finishing separately?", "Yes, the necessary repair and optional surface upgrade can be identified as distinct parts of the proposed scope."]],
    guides: ["retape-or-replace-garage-drywall", "garage-drywall-tape-repair-keeps-failing"]
  }
];

export const garageCities = cityContent.map(city => {
  const coverage = garageNeighbourhoodCoverage[city.slug];
  return coverage ? { ...city, coverage, faqs: [...city.faqs, coverage.faq] } : city;
});
