export const garageHub = {
  title: "Garage Drywall Repair & Re-Taping",
  metaTitle: "Garage Drywall Repair | Re-Taping & Finishing",
  description: "Repair peeling tape, cracked seams and damaged garage drywall. EPF provides re-taping, board repairs and smooth finishing, with primer and painting options.",
  intro: "Peeling tape, cracked seams and rough garage walls need a repair plan that starts beneath the final coat. EPF Pro Services assesses failed joints, repairs or replaces damaged drywall where needed, then re-tapes and refinishes the agreed areas for primer or painting.",
  answer: "Solid garage board with a failed seam may be suitable for local re-taping. Soft, loose or badly damaged board needs assessment before finishing. You can request isolated repairs or a broader garage refinishing scope, with the stopping point clearly defined in your quote.",
  sections: [
    { title: "Garage drywall problems we repair", paragraphs: [
      "A garage can have several different surface problems at once. Paper tape may curl away from a wall while another seam has a hairline crack and a nearby shelf has left an impact hole. Those defects should not automatically receive the same treatment. We review where the damage is, whether the surrounding board is sound and what finish you want afterward.",
      "Peeling, bubbling or loose drywall tape needs a bond assessment. Cracked seams and failed joints may require the affected reinforcement to be rebuilt. A visible tape line through paint can instead be a surface-shape or decorating problem. Rough fastener spots, narrow compound ridges and old patches also need to be distinguished from actual movement or detachment.",
      "Holes and impact damage may be repaired with appropriately supported board patches. Damaged sheets or loose sections need a broader scope when they cannot provide a reliable finishing base. With staining or water-damaged drywall, the moisture source must be addressed and the affected construction assessed before cosmetic repair. A photograph helps explain the problem but cannot confirm concealed conditions."
    ]},
    { title: "Garage drywall tape repair and re-taping", paragraphs: [
      "When homeowners describe drywall tape coming off, falling down or separating from the ceiling, the visible strip is only part of the repair question. Compound applied over loose tape still relies on the failed layer beneath it. We assess the affected length and the surrounding joint before deciding what can remain and what needs removal.",
      "Where re-taping is appropriate, the scope can include removing failed material, preparing the joint, correcting the board attachment or damaged edge as necessary, and installing suitable new reinforcement. Appropriate compound coats then build a gradual transition into the surrounding surface. Corners, fasteners and adjoining repairs are included when identified in the quote.",
      "A shallow scratch over a sound joint may only need surface correction. A detached strip is a different condition. We explain that distinction so you understand why a repair may extend beyond the short piece of tape visible in your photo. The aim is to correct the failed area and rebuild its finish using suitable materials, rather than promise that every existing joint will behave like new construction."
    ]},
    { title: "Garage drywall repair or replacement?", paragraphs: [
      "Localized repair is worth considering when the board is secure and sound, the defect is limited and a practical transition can be made into the retained surface. Examples include a failed taped joint on otherwise intact panels, an isolated impact hole, a small old patch or a cosmetic ridge. The decision should follow condition, not simply the age of the garage.",
      "Replacement may be needed where board has lost integrity, attachment is compromised, water damage is extensive or the installation cannot support a dependable repair. The replacement boundary should reach suitable construction and allow the specified joint treatment. Removing a narrow strip just to keep the patch small is not necessarily the best scope.",
      "Visible sagging, continuing movement or uncertainty about the supporting construction needs the appropriate professional assessment. EPF does not diagnose structural performance from website photos. If the cause lies beyond drywall finishing, that work must be coordinated before the repaired surface is closed or decorated."
    ]},
    { title: "Improve rough builder-grade garage drywall", paragraphs: [
      "Some garages were originally finished only for their intended utility use. Exposed compound, visible screw treatment and rough joints do not by themselves establish defective construction. If you now want a cleaner workshop or painted storage space, the appearance target may be different from the original specification.",
      "We can assess rough joints, narrow mudding, uneven patches, fastener imperfections and transitions for additional finishing. Sound existing work may be retained and blended; loose tape or unstable coating must be addressed before smoothing proceeds. A whole-wall skim is an option in some scopes, but it is not a replacement for repairing an unreliable joint.",
      "Share how the garage will be used and where lights or shelving will sit. A main wall beside a workbench may deserve a different appearance discussion from a concealed storage corner. We put the selected surfaces and finish expectations in the quote so a garage improvement does not depend on an undefined promise to make everything perfect."
    ]},
    { title: "Garage drywall finishing and the painting handoff", paragraphs: [
      "Finishing progresses through appropriate joint preparation, tape bedding, compound coats, feathering and surface refinement. Broad transitions help repaired joints blend into the retained board. Sanding refines that shape; it cannot fill a low area or make detached material bond again. Dust removal and inspection come before the chosen primer system.",
      "Level 4 and Level 5 describe specified finishing treatments. Level 4 is a common starting point for many smooth painted surfaces under suitable lighting and decoration. Level 5 adds a thin skim coat across the full surface after the required joint treatment, helping reduce differences between board paper and finished joints under demanding conditions. Every garage does not need Level 5.",
      "Neither finish label certifies a wall assembly or corrects uneven framing. Paint sheen, colour, light direction and the original surface influence the result. For demanding decoration, discuss a representative sample and the conditions for final review. Primer and finish paint are separate scope items unless included explicitly."
    ]},
    { title: "Garage walls and garage ceilings need different access plans", paragraphs: [
      "Wall repairs often involve shelves, stored equipment, workbenches and vehicle clearance. Show us the wall behind movable storage as well as the most visible damage. A small patch can require a wider finishing area, and repainting may need to extend to a corner or other natural boundary. Decide which belongings will be removed before work begins.",
      "Ceiling repairs can involve loose seam tape, old access openings, cracked joints and previous patches. Overhead access must account for the garage door, its tracks, lighting and any installed equipment. Do not move or alter springs, tracks or electrical fixtures to make a repair accessible; use the appropriate qualified trade where changes are necessary.",
      "Sagging or visibly loose ceiling board is not a routine paint-preparation item. Keep clear of a suspect area and arrange assessment before using the space beneath it. A ceiling quote should identify safe access, any necessary coordination, the repair boundary and whether painting covers a local area or the full ceiling plane."
    ]},
    { title: "Our garage drywall repair process", paragraphs: [
      "We start with your photos and a description of the problem, then confirm the assessment needed for a written scope. Wide views show access and room layout; close views show the affected joints. We identify the intended repair areas, visible uncertainties and whether another issue must be resolved first.",
      "The work plan covers protection and access before material is disturbed. Failed tape or damaged board is removed where required. Appropriate board corrections or replacement establish the base, followed by joint preparation, re-taping and successive compound coats. Each step depends on the selected products and the condition of the previous application.",
      "Feathering and sanding prepare the agreed surface. EPF uses dust-control and HEPA vacuum sanding where appropriate, alongside protection and cleanup. Collection reduces dust; it does not make renovation dust-free. Primer, touch-ups and painting are completed when included, followed by review under the agreed room lighting.",
      "Drying intervals are part of the schedule. A garage that is cold, damp or regularly opened to outdoor conditions may need a different work window from a conditioned interior room. We plan around suitable product conditions rather than treat the setting time printed on a bag as the completion time for the garage."
    ]},
    { title: "Localized repair or full garage refinishing", paragraphs: [
      "A localized scope can suit several peeling seams, a discrete wall patch or an individual ceiling joint when the remaining surface is acceptable. Name each included area and the blending boundary. If the homeowner plans to paint afterward, identify who will inspect primer and handle any necessary finishing corrections.",
      "Broader refinishing may be useful when failed tape is widespread, rough joints run across several walls, numerous previous patches need blending or the goal is a consistently finished garage. We assess retained surfaces first, then separate essential repairs from the optional appearance upgrade. A larger finishing scope does not mean every board must be removed.",
      "Ask for alternatives that reach clearly different outcomes: repair the listed defects, finish selected visible surfaces, or refinish the agreed garage walls and ceiling. Compare what is included in each option. This is more useful than comparing one isolated patch price with a complete prime-and-paint package."
    ]},
    { title: "Why garage tape and seams can fail", paragraphs: [
      "Possible contributors include an inadequate original bond, damage, loose board, movement, moisture or the condition of a previous repair. Seasonal conditions can affect materials and finishing readiness, but a crack alone does not prove its cause. A repeated defect deserves a review of what happened before it returned.",
      "Tell us when the issue first appeared, whether it changes with the season, and whether water or another trade's work was involved. Keep any previous repair photos and product details. That history helps distinguish a finish problem from a condition that needs investigation outside the drywall scope.",
      "Painting over the evidence before assessment can make that review harder. Take photographs and leave uncertain material for inspection rather than pulling down strips or aggressively sanding. An appropriate repair boundary can only be chosen once the affected joint and adjacent construction are understood."
    ]},
    { title: "Attached garages and existing construction", paragraphs: [
      "An attached garage can contain wall and ceiling assemblies with requirements beyond surface appearance. Before substantial replacement or alteration, the relevant existing construction should be evaluated and applicable requirements confirmed. The correct detail depends on the project; there is no single board thickness or finish level that this page can prescribe for every garage.",
      "Keep required service access identifiable and share available drawings or previous renovation information. If a proposed repair changes an assembly, involves uncertain concealed conditions or reveals ongoing moisture or movement, obtain direction from the appropriate professional. The finishing specification and the construction requirements are separate parts of the job."
    ]},
    { title: "What changes the garage repair estimate?", paragraphs: [
      "The amount of failed tape, board condition, ceiling height, work access and selected finish all affect the scope. A few long seams are not equivalent to the same length spread around corners and overhead obstructions. Garage floor area alone does not describe repair labour or how much wall needs preparation.",
      "The quote should separate necessary repairs, replacement where required, finishing, protection, cleanup and any primer or painting. A small job may still involve several visits. No fixed garage repair rate is advertised here because the work can range from a local joint repair to significant board replacement and refinishing.",
      "For an estimate, send your city, wide garage views, ceiling and wall photos, close-ups of defects, approximate dimensions and the planned finish. Mention stored items, access restrictions, previous repairs and any unresolved moisture. We can then discuss the assessment and a scope suited to your actual garage."
    ]}
  ],
};
export const garageFaqs = [
  ["Why is my garage drywall tape peeling?", "A poor bond, damaged or loose board, moisture or earlier repair preparation may contribute. The visible strip does not identify the cause by itself; assessment should include the affected joint and adjacent board."],
  ["Can peeling drywall tape be repaired?", "Often, if the underlying construction is suitable. Failed material may need removal, joint preparation and new reinforcement before compound coats and surface finishing."],
  ["Does all old tape have to be removed before re-taping?", "Not automatically. Sound work may remain, while loose or unsuitable material needs an appropriate repair boundary. The extent should be assessed rather than chosen only from the exposed edge."],
  ["Why are my garage drywall seams cracking?", "Possible causes include joint failure, board movement, moisture or previous repair methods. A recurring or changing crack needs evaluation before another cosmetic fill."],
  ["Can you repair garage ceiling tape?", "EPF can assess ceiling tape and joint repairs, including access around door tracks and fixtures. Loose or sagging board needs assessment before normal finishing proceeds."],
  ["Should a crack be filled or re-taped?", "A surface defect over a sound joint may need limited correction. Failed reinforcement or an unstable base requires a different repair. The condition beneath the line guides the decision."],
  ["Can you replace only one damaged drywall section?", "A localized replacement can be considered where surrounding construction is sound and the repair can be properly supported and finished. Confirm the required assembly and painting boundaries."],
  ["When does garage drywall need replacement?", "Replacement may be needed for severely damaged, compromised or inadequately attached board. Moisture, support and existing assembly requirements must be considered before choosing the boundary."],
  ["Can unfinished garage drywall be made smooth?", "Sound board can often receive additional joint finishing or suitable skim work. Existing loose tape, damaged areas and unsuitable coatings should be addressed first."],
  ["Can rough builder finishing be improved?", "Yes, the surface can be assessed for a cleaner appearance specification. Original utility finishing and a new smooth painted finish are different targets; the scope should explain the additional work."],
  ["Why did my previous repair crack again?", "The original cause may remain, or the prior repair may not have addressed all failed material. Record when it returned and arrange assessment rather than assuming another coat will resolve it."],
  ["Can you repair the garage before painting?", "Yes. Define whether EPF stops at sanded drywall, includes primer or completes painting. Agree on inspection and touch-up responsibilities before the coating stage."],
  ["What finish level should I choose?", "Consider lighting, paint and expected appearance. Level 4 may suit many painted surfaces; Level 5 may help with demanding decoration. Neither replaces construction requirements or correction of the underlying board."],
  ["Can water-damaged garage drywall be repaired?", "The moisture source must first be addressed and affected materials assessed. Some areas may need replacement. Cosmetic finishing should follow that decision, not conceal an unresolved problem."],
  ["Can I send pictures for an estimate?", "Yes. Use the existing quote form with your city, dimensions and a description. Include a link to photos if available, or mention that you have photos to share so EPF can arrange the next step."]
];
