"use client";
import { useState } from "react";
import ResponsiveImage from "@/components/ResponsiveImage";
const stages=[
{phase:'01 / START THE CONVERSATION',title:'Start with a few photos.',intro:'Show us the rooms you’d like to refresh. We’ll talk through the ceiling condition, your goals, and your preferred timing.',work:['Review the rooms, ceiling texture, and visible repairs.','Discuss a preliminary scope and arrange a visit when needed.','Identify any testing needed before disturbing older materials.'],you:'Show us your space.',part:'Share a wide photo of each room, close-ups of any damage, your location, and the best way to reach you.',milestone:'We understand what you want to change.'},
{phase:'02 / MAKE IT CLEAR',title:'A plan you can say yes to.',intro:'An on-site assessment helps turn the initial conversation into a clear scope, price, and schedule.',work:['Check room sizes, access, and surface condition.','Set out the work and inclusions in a written quote.','Discuss preparation, finish choices, and a start date.'],you:'Review the details.',part:'Ask questions, confirm the scope you want, and choose an agreed start date. Mention any building rules or access restrictions.',milestone:'You know what is included before work begins.'},
{phase:'03 / PREPARE THE SPACE',title:'Your home comes first.',intro:'Protection and access are planned before the main work gets underway.',work:['Protect floors, furniture, and surrounding areas as agreed.','Set up containment and dust-control equipment.','Confirm any required testing is resolved before disturbance.'],you:'Keep the work area clear.',part:'Follow your agreed preparation list and keep children and pets away from the work zone. Let us know about any access concerns.',milestone:'The work area is prepared for the next stage.'},
{phase:'04 / BRING IT TOGETHER',title:'From texture to a smooth finish.',intro:'The agreed removal or resurfacing work is followed by careful surface preparation and finishing.',work:['Remove or resurface texture according to the assessed scope.','Repair, skim, sand, and inspect the surface.','Apply primer and any finish painting included in your quote.'],you:'Give the finish time.',part:'Allow for drying between stages, keep the area accessible, and confirm any outstanding colour or finish choices.',milestone:'The surface is ready for a final inspection.'},
{phase:'05 / THE FINAL WALKTHROUGH',title:'Take a look. Take it all in.',intro:'We finish with clean-up and a walkthrough so you can see the result and ask any final questions.',work:['Remove protection and clean the work area.','Review the finish with you and identify any touch-ups.','Explain relevant care guidance and the project handover.'],you:'Walk through with us.',part:'Look over the work, point out anything you want to discuss, and ask how to care for the freshly finished surfaces.',milestone:'You understand the finished work and next steps.'}
];
export default function ProcessExperience({steps,faqs}) {
const [active,setActive] = useState(0);
const [checked,setChecked] = useState(0);
return <div id="epf-process">
<div className="ep-hero"><div className="ep-hero-copy"><div className="ep-kicker">Your home. Our process.</div><h1>A fresh start.<br /><em>A clear plan.</em></h1><h2 className="ep-seo-heading">Popcorn Ceiling Removal — The EPF Way</h2><p>From your first photos to your finished ceiling, know what to expect—and who takes care of what.</p><div className="ep-actions"><a className="ep-primary" href="#ep-journey">See how it works <span aria-hidden="true">↓</span></a><a className="ep-text-link" href="sms:6479236784">Text us your photos ↗</a></div></div><figure className="ep-hero-photo"><ResponsiveImage src="/our-process/finished-staircase.webp" priority sizes="(max-width: 720px) 90vw, 45vw" alt="Smooth finished ceiling above a curved staircase from EPF’s project gallery" /><figcaption>The finish you’re working toward.<span>From the EPF Pro Services project gallery</span></figcaption></figure></div>
<div className="ep-reassurance"><span><span aria-hidden="true">✓</span> A scope you understand</span><span><span aria-hidden="true">✓</span> Protection before the work</span><span><span aria-hidden="true">✓</span> A walkthrough together</span></div>
<section id="ep-journey"><div className="ep-section-head"><div><div className="ep-kicker">From hello to handover</div><h2>Your project, in five stages.</h2></div><p>Choose a stage to see what happens and what you’ll need to do.</p></div>
<div className="ep-stage-nav" role="group" aria-label="Explore project stages"><button type="button" onClick={() => setActive(0)} aria-pressed={active === 0} aria-controls="ep-stage-panel"><span>01</span><strong>Tell us<br />about it</strong></button><button type="button" onClick={() => setActive(1)} aria-pressed={active === 1} aria-controls="ep-stage-panel"><span>02</span><strong>Agree<br />the plan</strong></button><button type="button" onClick={() => setActive(2)} aria-pressed={active === 2} aria-controls="ep-stage-panel"><span>03</span><strong>Protect<br />your home</strong></button><button type="button" onClick={() => setActive(3)} aria-pressed={active === 3} aria-controls="ep-stage-panel"><span>04</span><strong>Create<br />the finish</strong></button><button type="button" onClick={() => setActive(4)} aria-pressed={active === 4} aria-controls="ep-stage-panel"><span>05</span><strong>Enjoy<br />your space</strong></button></div>
<div id="ep-stage-panel" aria-live="polite" aria-atomic="true">{stages.map((stage,index) => <div key={stage.phase} hidden={active !== index} className="ep-stage-layout" role="region" aria-label={stage.title}><div className="ep-stage-main"><div className="ep-kicker">{stage.phase}</div><h3>{stage.title}</h3><p>{stage.intro}</p><div className="ep-label">What we do</div><ul className="ep-work-list">{stage.work.map(item => <li key={item}>{item}</li>)}</ul></div><aside className="ep-your-part"><div><div className="ep-label">Your part</div><h3>{stage.you}</h3><p>{stage.part}</p></div><div className="ep-next-milestone">Before we move on<strong>{stage.milestone}</strong></div></aside></div>)}</div>
<div className="ep-step-controls"><span id="ep-step-count">Stage {active + 1} of 5</span><div><button type="button" id="ep-back" disabled={active === 0} onClick={() => setActive(index => Math.max(0,index - 1))}>← Previous</button><button type="button" id="ep-next" disabled={active === 4} onClick={() => setActive(index => Math.min(4,index + 1))}>Next stage →</button></div></div>
</section>
<section className="ep-prep"><div><div className="ep-kicker">A little preparation helps</div><h2>Ready for<br />day one.</h2><p>Your final preparation list will depend on the agreed scope. Here are three things to discuss before the crew arrives.</p><p className="ep-check-count" id="ep-prep-count" aria-live="polite">{checked} of 3 preparation items checked</p></div><div className="ep-checks"><label><input type="checkbox" onChange={event => setChecked(count => count + (event.target.checked ? 1 : -1))} /><span><strong>Room access &amp; belongings</strong><small>Agree what needs moving and which areas the crew will need to access.</small></span></label><label><input type="checkbox" onChange={event => setChecked(count => count + (event.target.checked ? 1 : -1))} /><span><strong>Pets, children &amp; daily routines</strong><small>Plan how your household will stay clear of the work area.</small></span></label><label><input type="checkbox" onChange={event => setChecked(count => count + (event.target.checked ? 1 : -1))} /><span><strong>Building access &amp; timing</strong><small>Discuss parking, condo access, and any building requirements.</small></span></label></div></section>
<section className="ep-faq"><div className="ep-faq-heading"><div className="ep-kicker">The things people ask us</div><h2>Let’s make<br />it clear.</h2><p>Have a question about your particular home? Talk it through with us.</p><a className="ep-text-link" href="tel:+16479236784">Call (647) 923-6784 ↗</a></div><div>{faqs.map(item => <details key={item.name}><summary>{item.name}</summary><p>{item.acceptedAnswer.text}</p></details>)}</div></section>
<section className="ep-original"><div className="ep-kicker">A closer look at the work</div><h2>Our detailed process</h2><p>Cleaner rooms. Flatter ceilings. Brighter homes. Dust-contained removal, Level-5 skim, prime and paint — delivered on a reliable schedule.</p>{steps.map(step => <details key={step.id}><summary>{step.title}</summary><p>{step.summary}</p><h3>What we do</h3><ul>{step.do.map(item => <li key={item}>{item}</li>)}</ul><h3>Your part</h3><ul>{step.you.map(item => <li key={item}>{item}</li>)}</ul></details>)}<div className="ep-area-links" aria-label="Popcorn ceiling removal service areas">{['Toronto','Mississauga','Oakville','Burlington','Hamilton','Milton','Etobicoke'].map(city => <a key={city} href={'/popcorn-ceiling-removal/'+city.toLowerCase()}>{city}</a>)}</div></section><div className="ep-cta"><div><div className="ep-kicker">Your next step is simple</div><h2>Tell us about your space.</h2><p>Serving the GTA and surrounding communities. Don’t see your area? <a href="/contact/">Contact us directly</a> to confirm availability.</p></div><a className="ep-primary" href="/quote/">Let’s plan your project ↗</a></div>
</div>;
}
